### ISSUE TITLE
[lilmermaid-13] Start chain from v1.0.0rc6

### ISSUE THREAD

**Issue by dualsystems** [e-money/launch#17]
```
ngm-testnet@hw:~$ cosmovisor start --x-crisis-skip-assert-invariants
8:29PM INF starting ABCI with Tendermint
8:29PM INF Starting multiAppConn service impl=multiAppConn module=proxy
8:29PM INF Starting localClient service connection=query impl=localClient module=abci-client
8:29PM INF Starting localClient service connection=snapshot impl=localClient module=abci-client
8:29PM INF Starting localClient service connection=mempool impl=localClient module=abci-client
8:29PM INF Starting localClient service connection=consensus impl=localClient module=abci-client
8:29PM INF Starting EventBus service impl=EventBus module=events
8:29PM INF Starting PubSub service impl=PubSub module=pubsub
8:29PM INF Starting IndexerService service impl=IndexerService module=txindex
8:29PM INF ABCI Handshake App Info hash="���&�\\�Eg?�h�%k�\x05�n��\"\rŮ|9�����" height=319 module=consensus protocol-version=0 software-version=
8:29PM INF ABCI Replay Blocks appHeight=319 module=consensus stateHeight=319 storeHeight=320
8:29PM INF Replay last block using real app module=consensus
8:29PM ERR UPGRADE "v1.0.0-RC7" NEEDED at height: 320: 
starting to take backup of data directory at time 2021-09-04 20:29:37.045440337 +0300 EEST m=+0.311936863backup saved at location: /home/ngm-testnet/data-backup-2021-9-4, completed at time: 2021-09-04 20:29:37.046140658 +0300 EEST m=+0.312637096
time taken to complete the backup: 700.233µsbinary not present, downloading disabled: cannot stat dir /home/ngm-testnet/cosmovisor/upgrades/v1.0.0-RC7/bin/emd: stat /home/ngm-testnet/cosmovisor/upgrades/v1.0.0-RC7/bin/emd: no such file or directory

```

Need upgrade to v1.0.0RC7:

```
ngm-testnet@hw:~$ mkdir -p /home/ngm-testnet/cosmovisor/upgrades/v1.0.0-RC7/bin
ngm-testnet@hw:~$ cosmovisor start --x-crisis-skip-assert-invariants
8:30PM INF starting ABCI with Tendermint
8:30PM INF Starting multiAppConn service impl=multiAppConn module=proxy
8:30PM INF Starting localClient service connection=query impl=localClient module=abci-client
8:30PM INF Starting localClient service connection=snapshot impl=localClient module=abci-client
8:30PM INF Starting localClient service connection=mempool impl=localClient module=abci-client
8:30PM INF Starting localClient service connection=consensus impl=localClient module=abci-client
8:30PM INF Starting EventBus service impl=EventBus module=events
8:30PM INF Starting PubSub service impl=PubSub module=pubsub
8:30PM INF Starting IndexerService service impl=IndexerService module=txindex
8:30PM INF ABCI Handshake App Info hash="���&�\\�Eg?�h�%k�\x05�n��\"\rŮ|9�����" height=319 module=consensus protocol-version=0 software-version=
8:30PM INF ABCI Replay Blocks appHeight=319 module=consensus stateHeight=319 storeHeight=320
8:30PM INF Replay last block using real app module=consensus
8:30PM ERR UPGRADE "v1.0.0-RC7" NEEDED at height: 320: 
starting to take backup of data directory at time 2021-09-04 20:30:47.927548468 +0300 EEST m=+0.309616766backup saved at location: /home/ngm-testnet/data-backup-2021-9-4, completed at time: 2021-09-04 20:30:47.928194702 +0300 EEST m=+0.310263033
time taken to complete the backup: 646.267µs8:30PM INF starting ABCI with Tendermint
8:30PM INF Starting multiAppConn service impl=multiAppConn module=proxy
8:30PM INF Starting localClient service connection=query impl=localClient module=abci-client
8:30PM INF Starting localClient service connection=snapshot impl=localClient module=abci-client
8:30PM INF Starting localClient service connection=mempool impl=localClient module=abci-client
8:30PM INF Starting localClient service connection=consensus impl=localClient module=abci-client
8:30PM INF Starting EventBus service impl=EventBus module=events
8:30PM INF Starting PubSub service impl=PubSub module=pubsub
8:30PM INF Starting IndexerService service impl=IndexerService module=txindex
8:30PM INF ABCI Handshake App Info hash="���&�\\�Eg?�h�%k�\x05�n��\"\rŮ|9�����" height=319 module=consensus protocol-version=0 software-version=
8:30PM INF ABCI Replay Blocks appHeight=319 module=consensus stateHeight=319 storeHeight=320
8:30PM INF Replay last block using real app module=consensus
8:30PM INF applying upgrade "v1.0.0-RC7" at height: 320
8:30PM INF Upgraded to
8:30PM INF Inflation minted coins echf=98 edkk=246 eeur=2060 enok=369 esek=246 module=x/inflation ungm=5271700
8:30PM INF minted coins from module account amount=98echf,246edkk,2060eeur,369enok,246esek,5271700ungm from=inflation module=x/bank
panic: UnmarshalJSON cannot decode empty bytes

goroutine 1 [running]:
github.com/cosmos/cosmos-sdk/x/params/types.Subspace.Get({{0x1e9b118, 0xc000edda50}, 0xc000011e00, {0x1e45868, 0xc001226c10}, {0x1e458b8, 0xc001226ce0}, {0xc001216770, 0x4, 0xf}, ...}, ...)
        /home/ngm-testnet/go/pkg/mod/github.com/cosmos/cosmos-sdk@v0.42.9/x/params/types/subspace.go:109 +0x319
github.com/cosmos/cosmos-sdk/x/params/types.Subspace.GetParamSet({{0x1e9b118, 0xc000edda50}, 0xc000011e00, {0x1e45868, 0xc001226c10}, {0x1e458b8, 0xc001226ce0}, {0xc001216770, 0x4, 0xf}, ...}, ...)
        /home/ngm-testnet/go/pkg/mod/github.com/cosmos/cosmos-sdk@v0.42.9/x/params/types/subspace.go:222 +0x145
github.com/e-money/bep3/module/keeper.Keeper.GetParams(...)
        /home/ngm-testnet/go/pkg/mod/github.com/e-money/bep3@v0.3.4/module/keeper/params.go:11
github.com/e-money/bep3/module/keeper.Keeper.GetAssets({{0x1e45868, 0xc001226cd0}, {0x1e9b118, 0xc000edda50}, {{0x1e9b118, 0xc000edda50}, 0xc000011e00, {0x1e45868, 0xc001226c10}, {0x1e458b8, ...}, ...}, ...}, ...)
        /home/ngm-testnet/go/pkg/mod/github.com/e-money/bep3@v0.3.4/module/keeper/params.go:48 +0x125
github.com/e-money/bep3/module/keeper.Keeper.UpdateTimeBasedSupplyLimits({{0x1e45868, 0xc001226cd0}, {0x1e9b118, 0xc000edda50}, {{0x1e9b118, 0xc000edda50}, 0xc000011e00, {0x1e45868, 0xc001226c10}, {0x1e458b8, ...}, ...}, ...}, ...)
        /home/ngm-testnet/go/pkg/mod/github.com/e-money/bep3@v0.3.4/module/keeper/asset.go:159 +0x98
github.com/e-money/bep3/module.BeginBlocker({{0x1e756b8, 0xc0011d2390}, {0x1e98fb8, 0xc000c02f40}, {{0xb, 0x0}, {0xc000e01990, 0xd}, 0x140, {0xa2eb0d8, ...}, ...}, ...}, ...)
        /home/ngm-testnet/go/pkg/mod/github.com/e-money/bep3@v0.3.4/module/abci.go:18 +0x278
github.com/e-money/bep3/module.AppModule.BeginBlock(...)
        /home/ngm-testnet/go/pkg/mod/github.com/e-money/bep3@v0.3.4/module/module.go:165
github.com/cosmos/cosmos-sdk/types/module.(*Manager).BeginBlock(_, {{0x1e756b8, 0xc0011d2390}, {0x1e98fb8, 0xc000c02f40}, {{0xb, 0x0}, {0xc000e01990, 0xd}, 0x140, ...}, ...}, ...)
        /home/ngm-testnet/go/pkg/mod/github.com/cosmos/cosmos-sdk@v0.42.9/types/module/module.go:338 +0x218
github.com/e-money/em-ledger.(*EMoneyApp).BeginBlocker(_, {{0x1e756b8, 0xc0011d2390}, {0x1e98fb8, 0xc000c02f40}, {{0xb, 0x0}, {0xc000e01990, 0xd}, 0x140, ...}, ...}, ...)
        /home/ngm-testnet/make/em-ledger-1.0.0-RC7/app.go:494 +0x39b
github.com/cosmos/cosmos-sdk/baseapp.(*BaseApp).BeginBlock(_, {{0xc000e240e0, 0x20, 0x20}, {{0xb, 0x0}, {0xc000e01990, 0xd}, 0x140, {0xa2eb0d8, ...}, ...}, ...})
        /home/ngm-testnet/go/pkg/mod/github.com/cosmos/cosmos-sdk@v0.42.9/baseapp/abci.go:191 +0x8fc
github.com/tendermint/tendermint/abci/client.(*localClient).BeginBlockSync(_, {{0xc000e240e0, 0x20, 0x20}, {{0xb, 0x0}, {0xc000e01990, 0xd}, 0x140, {0xa2eb0d8, ...}, ...}, ...})
        /home/ngm-testnet/go/pkg/mod/github.com/tendermint/tendermint@v0.34.11/abci/client/local_client.go:274 +0x118
github.com/tendermint/tendermint/proxy.(*appConnConsensus).BeginBlockSync(_, {{0xc000e240e0, 0x20, 0x20}, {{0xb, 0x0}, {0xc000e01990, 0xd}, 0x140, {0xa2eb0d8, ...}, ...}, ...})
        /home/ngm-testnet/go/pkg/mod/github.com/tendermint/tendermint@v0.34.11/proxy/app_conn.go:81 +0x55
github.com/tendermint/tendermint/state.execBlockOnProxyApp({0x1e76330, 0xc000c67e60}, {0x1e891b0, 0xc000e030d0}, 0xc00000cb40, {0x1e99158, 0xc000e02530}, 0x13f)
        /home/ngm-testnet/go/pkg/mod/github.com/tendermint/tendermint@v0.34.11/state/execution.go:307 +0x3dd
github.com/tendermint/tendermint/state.(*BlockExecutor).ApplyBlock(_, {{{0xb, 0x0}, {0xc000e004d8, 0x7}}, {0xc000e00510, 0xd}, 0x1, 0x13f, {{0xc000e960e0, ...}, ...}, ...}, ...)
        /home/ngm-testnet/go/pkg/mod/github.com/tendermint/tendermint@v0.34.11/state/execution.go:140 +0x171
github.com/tendermint/tendermint/consensus.(*Handshaker).replayBlock(_, {{{0xb, 0x0}, {0xc000e004d8, 0x7}}, {0xc000e00510, 0xd}, 0x1, 0x13f, {{0xc000e960e0, ...}, ...}, ...}, ...)
        /home/ngm-testnet/go/pkg/mod/github.com/tendermint/tendermint@v0.34.11/consensus/replay.go:503 +0x23c
github.com/tendermint/tendermint/consensus.(*Handshaker).ReplayBlocks(_, {{{0xb, 0x0}, {0xc000e004d8, 0x7}}, {0xc000e00510, 0xd}, 0x1, 0x13f, {{0xc000e960e0, ...}, ...}, ...}, ...)
        /home/ngm-testnet/go/pkg/mod/github.com/tendermint/tendermint@v0.34.11/consensus/replay.go:416 +0x7ae
github.com/tendermint/tendermint/consensus.(*Handshaker).Handshake(0xc000e7a2d0, {0x1ea1008, 0xc00026e8f0})
        /home/ngm-testnet/go/pkg/mod/github.com/tendermint/tendermint@v0.34.11/consensus/replay.go:268 +0x3c8
github.com/tendermint/tendermint/node.doHandshake({_, _}, {{{0xb, 0x0}, {0xc000e004d8, 0x7}}, {0xc000e00510, 0xd}, 0x1, 0x13f, ...}, ...)
        /home/ngm-testnet/go/pkg/mod/github.com/tendermint/tendermint@v0.34.11/node/node.go:308 +0x1b8
github.com/tendermint/tendermint/node.NewNode(0xc000f42780, {0x1e54300, 0xc0010197c0}, 0xc000e023a0, {0x1e37900, 0xc000e98030}, 0x7feaabf41e50, 0x2, 0xc000e02500, {0x1e76330, ...}, ...)
        /home/ngm-testnet/go/pkg/mod/github.com/tendermint/tendermint@v0.34.11/node/node.go:715 +0x578
github.com/cosmos/cosmos-sdk/server.startInProcess(_, {{0x0, 0x0, 0x0}, {0x0, 0x0}, {0x0, 0x0}, {0x1e7d870, 0xc000edda50}, ...}, ...)
        /home/ngm-testnet/go/pkg/mod/github.com/cosmos/cosmos-sdk@v0.42.9/server/start.go:244 +0x625
github.com/cosmos/cosmos-sdk/server.StartCmd.func2(0xc000f60000, {0xc001000de0, 0x0, 0x1})
        /home/ngm-testnet/go/pkg/mod/github.com/cosmos/cosmos-sdk@v0.42.9/server/start.go:120 +0x193
github.com/spf13/cobra.(*Command).execute(0xc000f60000, {0xc001000dd0, 0x1, 0x1})
        /home/ngm-testnet/go/pkg/mod/github.com/spf13/cobra@v1.1.3/command.go:852 +0x60e
github.com/spf13/cobra.(*Command).ExecuteC(0xc000ec2f00)
        /home/ngm-testnet/go/pkg/mod/github.com/spf13/cobra@v1.1.3/command.go:960 +0x3ad
github.com/spf13/cobra.(*Command).Execute(...)
        /home/ngm-testnet/go/pkg/mod/github.com/spf13/cobra@v1.1.3/command.go:897
github.com/spf13/cobra.(*Command).ExecuteContext(...)
        /home/ngm-testnet/go/pkg/mod/github.com/spf13/cobra@v1.1.3/command.go:890
github.com/cosmos/cosmos-sdk/server/cmd.Execute(0x0, {0xc000161878, 0x16})
        /home/ngm-testnet/go/pkg/mod/github.com/cosmos/cosmos-sdk@v0.42.9/server/cmd/execute.go:36 +0x1d0
main.main()
        /home/ngm-testnet/make/em-ledger-1.0.0-RC7/cmd/emd/main.go:14 +0x2c
exit status 2
```

**Comment by mdyring** [comment]
Hello @dualsystems,

You should install the v1.0.0-RC9 binary to get up and running. Can you let me know where you found the instructions to use v1.0.0-RC6? (might be something outdated)

**Comment by mdyring** [comment]
Ah, I see the instructions did not include the upgrade binary.

Fixed now, please revisit https://github.com/e-money/networks/tree/master/lilmermaid-13#task-1-installation
